// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace proLanguages.Migrations
{
    [DbContext(typeof(proLanguageslanguagesContext))]
    partial class proLanguageslanguagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("languages.models.proLanguage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("developBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("releaseYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("usedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("proLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
